### ISSUE TITLE
When will the code for training be released?

### ISSUE THREAD

**Issue by sonnefred** [hyzhou404/HUGS#1]
Hi, thank you for releasing the code. Do you have any plan when the training code will be released? Thanks!

**Comment by hyzhou404** [comment]
Hello, due to certain constrains, we are unable to include the training scripts in this repository. However, they will be made available in our upcoming work which is not very far off.

**Comment by sonnefred** [comment]
> Hello, due to certain constrains, we are unable to include the training scripts in this repository. However, they will be made available in our upcoming work which is not very far off.

Ok, thanks!
