### ISSUE TITLE
About the preprocessing of the data

### ISSUE THREAD

**Issue by qianfanshen** [hyzhou404/HUGS#11]
I wonder how you get the point cloud in the [data](https://huggingface.co/datasets/hyzhou404/hugs_release) from the initial datasets, or how to generate the colmap, since i failed to generate them by using convert.py from the vanilla [3DGS](https://github.com/graphdeco-inria/gaussian-splatting)

**Comment by hyzhou404** [comment]
Sorry for late reply. Over the past few months, we developed a closed-loop simulator and benchmark named HUGSIM (https://arxiv.org/abs/2412.01718). We plan to share all the associated code in the HUGSIM repository, including training, data preprocessing, evaluation, and etc.
