### ISSUE TITLE
Any plan to release training code?

### ISSUE THREAD

**Issue by lemonci** [hyzhou404/HUGS#12]
I would like to work on your project. May I ask if you have any plan to release the training code? Thanks.

**Comment by LivingTom** [comment]
+1 the same question

**Comment by pklie** [comment]
+1

**Comment by hyzhou404** [comment]
Sorry for late reply. Over the past few months, we developed a closed-loop simulator and benchmark named HUGSIM (https://arxiv.org/abs/2412.01718). We plan to share all the associated code in the HUGSIM repository, including training, data preprocessing, evaluation, and etc.
