### ISSUE TITLE
How to use SIBR_viewer to view the output?

### ISSUE THREAD

**Issue by eggman-1024** [hyzhou404/HUGS#2]

**Comment by hyzhou404** [comment]
In our project, we removed SIBR_viewer and only save center positions and RGB colors of 3D Gaussians in the ply file. The complete information is stored in checkpoint files named "chkpnt*.pth". 
If you need to visualize 3D Gaussians in SIBR_viewer for some reason, you can load the checkpoint file and apply original "save_ply" function.

**Comment by eggman-1024** [comment]
ok, 感谢大佬及时回复！！！
