### ISSUE TITLE
rendering result of semantic is strange with waymo dataset

### ISSUE THREAD

**Issue by zuochongyan** [hyzhou404/HUGS#3]
thank you for your brilliant work! I download the waymo dataset, doing rendering and found some questions.
 -  for waymo dataset,  i could not add --affine, it seems affine model is not in ckpt, if add --affine, model.restore will set appearance_model to None and raise error

 - the result of rendering rgb,depth and optical is corrent, but the result of semantic is very strange.Could you check that the source code can directly generate correct semantic rendering?

![image](https://github.com/hyzhou404/HUGS/assets/9625061/3432574b-6730-4b79-959a-1f9f6c375b9e)

**Comment by hyzhou404** [comment]
It seems I uploaded the wrong checkpoint. Please wait while my double-check. Thanks for pointing it out, and sorry for the confusion.

**Comment by hyzhou404** [comment]
An incorrect checkpoint was uploaded previously. I've now reuploaded the correct checkpoint. Please redownload it and give it another try!

**Comment by zuochongyan** [comment]
thanks,the waymo dataset can render correct semantic now, the kitti seq seem to have the same problem.
![image](https://github.com/hyzhou404/HUGS/assets/9625061/5273f9ac-be8c-4f92-bd52-92ef72854e20)

**Comment by hyzhou404** [comment]
It is not unexpected that KITTI sequence cannot render correct semantic map. Because we didn't incorporate semantic supervision during the KITTI training process.
