### ISSUE TITLE
any plan for sharing the model?

### ISSUE THREAD

**Issue by JohnnyHan** [hyzhou404/HUGS#8]
there is only the data at Data & Checkpoints Download items, would you like to share the model, any plan?

**Comment by hyzhou404** [comment]
Sorry for late reply. Over the past few months, we developed a closed-loop simulator and benchmark named HUGSIM (https://arxiv.org/abs/2412.01718). We plan to share all the associated code in the HUGSIM repository, including training, data preprocessing, evaluation, and etc.
