### ISSUE TITLE
Can HUGS remove the car and build a pure street?

### ISSUE THREAD

**Issue by zzz5y** [hyzhou404/HUGS#9]
Amazing work!thanks for your work and hopefully to get your reple!

**Comment by hyzhou404** [comment]
Most of the dynamic vehicles can be removed, but we cannot remove static vehicles in HUGS, as scenes behind static vehicles lack of observation.

**Comment by zzz5y** [comment]
> Most of the dynamic vehicles can be removed, but we cannot remove static vehicles in HUGS, as scenes behind static vehicles lack of observation.

any code are related to edit the dynamic car?thanks a lot

**Comment by hyzhou404** [comment]
We haven't release code for editing dynamic vehicles. A naive method is manually changing the bounding box poses. We just  release the paper of closed-loop simulator HUGSIM (https://arxiv.org/abs/2412.01718). In HUGSIM, we generate dynamic vehicles trajectories automatically. The code for HUGSIM will be released later.

**Comment by zzz5y** [comment]
> We haven't release code for editing dynamic vehicles. A naive method is manually changing the bounding box poses. We just release the paper of closed-loop simulator HUGSIM (https://arxiv.org/abs/2412.01718). In HUGSIM, we generate dynamic vehicles trajectories automatically. The code for HUGSIM will be released later.

Congratulations! I look forward to and appreciate your work! I'm very curious about how your work addresses the issue of some surfaces of vehicles not being visible in 3D Gaussian splatting within autonomous driving scenarios? Also, in cases where the main vehicle experiences a significant shift, leading to blurring of dynamic objects and tearing in the sky, how are these issues optimized? Looking forward to your reply!Thanks a lot!

**Comment by zzz5y** [comment]
> > We haven't release code for editing dynamic vehicles. A naive method is manually changing the bounding box poses. We just release the paper of closed-loop simulator HUGSIM (https://arxiv.org/abs/2412.01718). In HUGSIM, we generate dynamic vehicles trajectories automatically. The code for HUGSIM will be released later.
> 
> Congratulations! I look forward to and appreciate your work! I'm very curious about how your work addresses the issue of some surfaces of vehicles not being visible in 3D Gaussian splatting within autonomous driving scenarios? Also, in cases where the main vehicle experiences a significant shift, leading to blurring of dynamic objects and tearing in the sky, how are these issues optimized? Looking forward to your reply!Thanks a lot!

I found the question explain in paper! thank you!
